### ISSUE TITLE
typing conlfict: store VueStore

### ISSUE THREAD

**Issue by christophmayrhofer** [ktsn/sinai#12]
I get the following error:

> Subsequent variable declarations must have the same type.  Variable 'store' must be of type 'VueStore<any, any, any, any> | undefined', but here has type 'Store<any> | undefined'.

It seems that the sinai VueStore Interface is conflicting with the vue Store interface

I am using nuxtjs. This might play a role.

**Comment by ktsn** [comment]
Well, this is because you are loading both Vuex and Sinai in your app.
I'm not sure we can fix it in Sinai since using both of them seems invalid situation.

**Comment by ktsn** [comment]
Looks like Nuxt.js core is coupled with Vuex so you should not use Sinai in Nuxt application.
If you want to use Sinai with SSR, you should create your own server.
