### ISSUE TITLE
Subscribed functions

### ISSUE THREAD

**Issue by DevoidCoding** [ktsn/sinai#13]
Actually, the subscribed functions are handle like `(path, args, state)`, but vuex handle them like `(path, state)`
In order to make vuex plugins compatible, shouldn't this be `(path, state, args)` ?

**Comment by ktsn** [comment]
Anyway, we need extra plugin adapter to let Sinai be compatible with Vuex plugin. Because Vuex's subscriber type is `(mutation: { type: string, ... }, state: S) => any` while Sinai's one is `(mutationPath: string[], payload: any[], state: S) => void`. They are completely different.
