### ISSUE TITLE
To use this.$store in Vue Component

### ISSUE THREAD

**Issue by bichikim** [ktsn/sinai#181]
Set up as below code
```
import * as Sinai from 'sinai'
import aside from './aside'
import Vue from 'vue'

Vue.use(Sinai)

const root = Sinai.module().child('aside', aside())

export const store =  Sinai.store(root, {
  strict: process.env.DEV,
})


class Fake {
  get store() {
    return store
  }
}

declare module 'vue/types/vue' {
  interface Vue {
    $store: typeof Fake.prototype.store
  }
}

export default () => (store)
```
Now you can use this.$store like below
```
  import {Component, Vue} from 'vue-property-decorator'
  import store from 'src/store'

  @Component
  export default class IndexPage extends Vue {

    meta: {

    }

    mounted() {
      console.log(store().state.aside.version)
    }
  }
```
![image](https://user-images.githubusercontent.com/13829322/75325888-f40fe600-58bc-11ea-89be-8282af2773e6.png)

**Comment by ktsn** [comment]
Sorry, what do you mean by this issue? Is this a bug report or feature request? I don't understand what the intention of this issue is.

**Comment by bichikim** [comment]
I'm sorry for not writing down my intentions.
I think `this.$store` type checking is not working without below code
```
declare module 'vue/types/vue' {
  interface Vue {
    $store: typeof Fake.prototype.store
  }
}
```
So Yes It just a tip for the problem

**Comment by ktsn** [comment]
Thanks for clarify. It's intentional not including the `$store` type as store instance type is different between each app and users need to specify it by themselves.
