### ISSUE TITLE
No definition for this.$store on new vue-cli TypeScript project

### ISSUE THREAD

**Issue by HendrikGrobler** [ktsn/sinai#19]
I created a  new project using version 3.0.0-beta.12 of the vue cli with Babel, TypeScript and vue-property-decorator. Then I  setup a super basic store as per your example in the readme file.

I then tried to use `this.$store` in the generated 'HelloWorld.vue' component, however it finds no definition for `this.$store` (Property '$store' does not exist on type 'HelloWorld').

It is probably worth noting that this method imports `Vue` from 'vue-property-decorator' instead of from 'vue' which may affect how the .d.ts declared stuff works.

As a side note, in your setup for VueJs tests you declare `$store` as type `any` which means when you use `this.$store` inside a component you lose all type hinting. Is this just for testing or does this library not support proper type hinting inside components?

Any help is appreciated, I've tried adding my own definitions, but haven't had much success. It would be very helpful to have an example of how to use this library in a base TypeScript project generated by the vue cli.

**Comment by ktsn** [comment]
It's intentional not to write `$store` type since it differs various projects. Users should declare their own store type by themselves. And also intentional not writing detailed docs because this lib is highly experimental, not production ready.

> As a side note, in your setup for VueJs tests you declare $store as type any which means when you use this.$store inside a component you lose all type hinting. Is this just for testing or does this library not support proper type hinting inside components?

It's just for testing.
