### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by nailfar** [ktsn/sinai#26]
**It does not work with vue-devtool**
![image](https://user-images.githubusercontent.com/12581226/57905330-b7807a00-78a8-11e9-9b34-aa312f371f45.png)
******************************************************************************************************
**proxyStore not return replaceState**
![image](https://user-images.githubusercontent.com/12581226/57905415-0f1ee580-78a9-11e9-9195-3dc968bd1577.png)
******************************************************************************************************

![image](https://user-images.githubusercontent.com/12581226/57905311-a33c7d00-78a8-11e9-9468-043661e4093d.png)
******************************************************************************************************
![image](https://user-images.githubusercontent.com/12581226/57905371-e4cd2800-78a8-11e9-8467-151bc5f2a5e5.png)

**Comment by nailfar** [comment]
sinai 0.2.4
vue-devtools  5.1.0

**Comment by ktsn** [comment]
Thanks for reporting this. Fixed in v0.2.6
