### ISSUE TITLE
Root module store type definition doesnt work with getters, actions, mutations

### ISSUE THREAD

**Issue by namnm** [ktsn/sinai#312]
Hi, here is the code copied from README. I have an issue that it says `counter` does not exist on `getters`, `actions` or `mutations`. Only `state` works though. The code added on a fresh vue2 app: sinai 0.2.6, typescript 3.9.3

<img width="998" alt="Screen Shot 2021-01-18 at 20 53 08" src="https://user-images.githubusercontent.com/8970908/104924064-81759080-59cf-11eb-9485-e3d109b245df.png">

If remove root then use `const store = createStore(counter)` then it works correctly, but afterward there's no point of combined root for complex use case.

**Comment by ktsn** [comment]
It works now.
